scale: 1
metatile: 1
name: "Labels and Roads"
bounds:
  - 1.39526
  - 47.9873
  - 3.59253
  - 49.2633
center:
  - 2.37681
  - 48.84949
  - 18
format: "png"
minzoom: 1
maxzoom: 20
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
overlay:
  active: true
  opacity: 1
  position: -1
Stylesheet:
- "style.mss"
source: 'tms://carto.data.gouv.fr/vector/all/{z}/{x}/{y}.mvt'
layers:
  - roads.geo
  - places
  - roads.label
